### PR TITLE
Test123123111111111111

### PR DESCRIPTION
**Pull request by wenlylinux**
body123123

### CODE REVIEW

**Comment by wenlylinux** [comment]
@wenlylinux ，您好，CI测试结果如下，可通过链接查看详细信息：
<table>
    <tr>
        <th colspan="2">测试用例</th><th>测试结果</th>
    </tr>
    <tr>
        <td colspan="2">check_specfile</td><td><a href=https://tone.openanolis.cn/ws/e6fkf2o4/test_result/5151>:x:失败</a></td>
    </tr>
    <tr>
        <td colspan="2">check_codestyle</td><td><a href=https://tone.openanolis.cn/ws/e6fkf2o4/test_result/5151>:white_check_mark:成功</a></td>
    </tr>
</table>

很遗憾，代码测试未通过，请点击链接查看详细信息，修改代码后，在本页面评论/retest重新进入测试流程。

**Comment by wenlylinux** [comment]
@wenlylinux ，您好，您无权进行此项操作。

**Comment by wenlylinux** [comment]
@wenlylinux ，您好，您无权进行此项操作。

**Comment by wenlylinux** [comment]
@wenlylinux ，您好，测试任务已经提交，请耐心等待测试结果。

**Comment by yqleng1987** [comment]
@wenlylinux , the test job has been submitted. Please wait in patience.

**Comment by yqleng1987** [comment]
@wenlylinux , The CI test is completed, please check result:
<table>
    <tr>
        <th colspan="2">Test Case</th><th>Test Result</th>
    </tr>
    <tr>
        <td colspan="2">merge-target-branch</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/7937>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">build-docker-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/7937>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/7937>:x:FAIL</a></td>
    </tr>
</table>

Sorry, your test job failed. Please get the details in the link.

**Comment by wenlylinux** [comment]
123

**Pull request closed without merging**
